#!/bin/bash

trap 'echo $LINENO: $BASH_COMMAND' ERR

nvchecker -c nvchecker.toml -l warning -t 3 \
    || exit 1

nvcmp -c nvchecker.toml | while read pkg oldver op newver; do
    test "$op" = '->' \
        || continue

    # is it a Formula or a Cask?
    path=$(compgen -G "Formula/$pkg.rb" || compgen -G "Casks/$pkg.rb") \
        || { echo "[$pkg] ERROR: $pkg.rb not found" >&2 ; continue ; }

    echo "[$pkg] updating from $oldver to $newver in $path"

    # create detached head based on github/main
    git fetch github \
        && git -c 'advice.detachedHead=false' checkout $(git rev-parse nvchecker) \
        || continue
    # FIXME : this should be github/main instead of nvchecker when going live

    # update version in URL
    gsed -i $path -e "/^  url / s/$oldver/$newver/" \
        || continue

    # get hash and update it
    sha256=`gawk '$1=="url" {print $2}' $path | sed 's/"//g' | xargs curl -sL | sha256sum - | gawk '{print $1}'`
    gsed -i $path -e "/^  sha256 / s/\".*\"/\"$sha256\"/" \
        || continue

    # create Git commit and push
    git add $path \
        && git commit -m "Update $pkg to $newver" \
        && git push github @:refs/heads/$pkg-$newver \
        || continue

    # create pr w pr-pull label
    pr_url=$(gh pr create -H $pkg-$newver -B main -l pr-pull -t $pkg-$newver -b "Update $pkg to $newver") \
        || continue
    echo "[$pkg] pull request is $pr_url"

    # wait for checks to pass
    until gh pr checks $pr_url &>/dev/null; do
        sleep 2.5
    done

    # update current version
    nvtake -c nvchecker.toml $pkg \
        || continue

    # we're done
    echo "[$pkg] success!"
done

# get back to normal
#git fetch github
#git checkout main
#git merge --no-ff github/main
